### ISSUE TITLE
TrackLink no longer working in v5.0.0

### ISSUE THREAD

**Issue by thefeli73** [knadh/listmonk#2448]
**Version:**
 - listmonk: v5.0.0
 - OS: Docker

**Description of the bug and steps to reproduce:**
Tracked links in old and new campaigns no longer work and cause an error when trying to preview the campaign, when using this format: {{ TrackLink "https://link.com" }}. the @TrackLink syntax seems to still work, but the former syntax creates this error:
`{"message":"Error rendering message: template: content:49:27: executing \"content\" at \u003cTrackLink\u003e: wrong number of args for TrackLink: want 2 got 1"}`

**Comment by guiand888** [comment]
Version:

- listmonk: v5.0.0
- OS: Docker

I can confirm I am getting the same errors.

With an html template where the TrackLink is such as:

```html
<a href="{{ TrackLink `https://example.com` }}">My link</a>

```

I am getting the following errors:

```
ampaigns.go:581: error rendering message: template: base:303:104: executing "base" at <TrackLink>: wrong number of args for TrackLink: want 2 got 1
campaigns.go:520: error sending test message: code=404, message=Error rendering message: template: base:303:104: executing "base" at <TrackLink>: wrong number of args for TrackLink: want 2 got 1
```

For now the workaround has been to use the other TrackLink syntax, which doesn't seem to generate errors:

```html
<a href="https://example.com@TrackLink">My link</a>

Would be good to know if both syntax are still supported, as the docs still provide both options: https://listmonk.app/docs/templating/

**Comment by aurelien-ephe** [comment]
Hi,
I'm facing the same issue with tracklink feature (same version).
But my struggle is with some complexes characters in link i want to be tracked.
With something like "**htts://foo.bar/search?fulltext=campus&f[0]=themes:2&f[1]=themes:1706**". The traclking checkbox add @Tracklink at the end of but it's not tracked at all (and generate bad redirection in this case).
And if i want to wrap the link as "**{{ TrackLink "https://www.ephe.psl.eu/recherche?fulltext=campus&f[0]=themes:2&f[1]=themes:1706"}}**", i can't register the content because of : 
`[...] error compiling message: template: content:1: unexpected "%" in command"`.

**Comment by knadh** [comment]
Please upgrade to [v5.0.1](https://github.com/knadh/listmonk/releases/tag/v5.0.1).

**Comment by thefeli73** [comment]
> Please upgrade to [v5.0.1](https://github.com/knadh/listmonk/releases/tag/v5.0.1).
At least the preview issue seems to be fixed, haven’t tried anything else. Thanks!

**Comment by ericcumbee** [comment]
This issue is still persisting for me on [v5.0.1] after upgrading from 4.

**Comment by etranger7** [comment]
@knadh I was having this issue with {{ tracklink }} by itself, I updated to 5.0.2 and that got resolved.
However, when I'm trying to nest expressions as it's suggested here https://github.com/knadh/listmonk/issues/1772
I'm still getting this error.

**Comment by titouan13** [comment]
If you're trying to nest expressions as suggested in #1772 
here is the updated code as explained in #2492 
`
{{ $link := print "https://example.com?utm_campaign=" .Campaign.Name }}
<a href="{{ TrackLink $link . }}">Click here</a>
`

**Comment by dhaneshmarch** [comment]
I upgraded from v2.5.1 to v5.1.0. Getting same error on all my older templates. 

`{"message":"Error rendering message: template: content:52:20: executing \"content\" at \u003cTrackLink\u003e: wrong number of args for TrackLink: want 2 got 1"}`

**Comment by etranger7** [comment]
@dhaneshmarch 

Here is how you can get around that error. This adds a second argument. I tested it on my system with Listmonk 6.0.0 and it works

```
{{ $link := print "https://www.example.com?uuid=" .Subscriber.UUID }}
<a href="{{ TrackLink $link . }}">Link Text</a>
```
