### ISSUE TITLE
SQL migration issues from 4.1.0 to 5.0.3

### ISSUE THREAD

**Issue by franc00018** [knadh/listmonk#2566]
**Version:**
 - listmonk: [eg: v5.0.3]
 - OS: [e.g. Debian]

**Description of the bug and steps to reproduce:**
There were some missing elements in the database after migration from 4.1.0 to 5.0.3.
Here are successive error messages and resolution step as a SQL query in the PostgreSQL database.
I don't know if this is sufficient, but this allowed me to start the app and use it like before.
These are consecutive bugs. The next one appears when the previous one is fixed.

Bug 1

```bash
listmonk@SERVER:~$ ./listmonk
2025/07/12 04:09:46.896716 main.go:106: v5.0.3 (48643aa9 2025-07-06T16:14:03Z, linux/amd64)
2025/07/12 04:09:46.896939 init.go:169: reading config: config.toml
2025/07/12 04:09:46.897252 init.go:309: connecting to db: localhost:5432/listmonk
2025/07/12 04:09:47.026392 init.go:363: error preparing SQL queries: Error preparing query 'create-campaign': pq: invalid input value for enum template_type: "campaign_visual"
```

Resolved with

```sql
ALTER TYPE template_type ADD VALUE 'campaign_visual';
```

Bug 2

```bash
2025/07/12 04:22:03.196913 init.go:363: error preparing SQL queries: Error preparing query 'create-campaign': pq: column "body_source" does not exist
```

Resolved with

```sql
ALTER TABLE "templates"
ADD "body_source" text NULL;
```

Bug 3

```bash
2025/07/12 04:28:34.345204 init.go:363: error preparing SQL queries: Error preparing query 'create-campaign': pq: column "body_source" of relation "campaigns" does not exist
```

Resolved with

```sql
ALTER TABLE "campaigns"
ADD "body_source" text NULL;
```

Bug 4

```bash
2025/07/12 04:29:54.016773 init.go:363: error preparing SQL queries: Error preparing query 'update-campaign': pq: invalid input value for enum content_type: "visual"
```

Resolved with

```sql
ALTER TYPE content_type ADD VALUE 'visual';
```

**Comment by knadh** [comment]
This is very strange. When you ran `./listmonk --upgrade`, did you get any errors?

Every version ships with idempotent migrations (https://github.com/knadh/listmonk/blob/master/internal/migrations/v5.0.0.go). It's possible to migrate from the v0.1.0 release of listmonk to the latest with a single `--upgrade` command in the latest binary with no manual inputs.
