### ISSUE TITLE
After upgrade to v3.0.0, listmonk won't start due to 'error preparing SQL queries'

### ISSUE THREAD

**Issue by sonologic** [knadh/listmonk#1815]
A while ago, I installed a pre-release of v3 due to issues with the smtp backend (https://github.com/knadh/listmonk/issues/1629). I am now trying to upgrade to v3.0.0, but listmonk won't start:

```
2024/04/05 16:40:57 init.go:343: error preparing SQL queries: Error preparing query 'get-dashboard-charts': pq: relation "mat_dashboard_charts" does not exist
```

The database is up to date according to listmonk:

```
gmc@enterprise:~/docker/listmonk$ docker compose run app /listmonk/listmonk --upgrade --yes
WARN[0000] /home/gmc/docker/listmonk/docker-compose.yaml: `version` is obsolete 
2024/04/05 16:46:41 main.go:102: v3.0.0 (f9120d9 2024-02-04T11:20:27Z, linux/amd64)
2024/04/05 16:46:41 init.go:150: reading config: config.toml
2024/04/05 16:46:41 init.go:289: connecting to db: 10.1.100.4:5432/listmonk
2024/04/05 16:46:41 upgrade.go:66: no upgrades to run. Database is up to date.
gmc@enterprise:~/docker/listmonk$ 
```

Anything I can do to get things back up and running?

**Comment by MaximilianKohler** [comment]
I looked at https://github.com/knadh/listmonk/blob/master/internal/migrations/v3.0.0.go, but I don't understand how to do that manually or why it would be necessary.

**Comment by sonologic** [comment]
@MaximilianKohler so my theory about why it was necessary is that I had v3-rc3 installed previously. That would already have had a migration of the databaste to v3.0.0. But since rc3, more was added to the migration, but since the database was already marked as 'up to date for v3.0.0' it would not re-apply the migration, and therefore the migration would only have partially updated the database schema to the actual v3.0.0 state.

As for the how, I simply copy-pasted the individual queries into the postgresql console.
